spring.application.name=vcommercestore

spring.datasource.url=jdbc:mysql://mysql-21b45054-vcommercestore7-2728.e.aivencloud.com:24486/vcommercestore
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
server.port=8181
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

user.profile.image.path=upload/images/users/profileimage/
user.profile.delfaultimage.path=upload/images/users/DefaultProfileImage/
spring.servlet.multipart.max-file-size=10MB
category.icons.path=upload/images/categories/Icons/
default.cateory.icons.path=upload/images/categories/DefaultCategoryIcon/
product.image.path=upload/images/Products/ProductImages/
product.default.image.path=upload/images/Products/Default/