spring.application.name=vcommercestore

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/vcommerce
spring.datasource.username=root
spring.datasource.password=Varun5041@

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
server.port=8181
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

user.profile.image.path=upload/images/users/profileimage/
user.profile.delfaultimage.path=upload/images/users/DefaultProfileImage/
spring.servlet.multipart.max-file-size=10MB
category.icons.path=upload/images/categories/Icons/
default.cateory.icons.path=upload/images/categories/DefaultCategoryIcon/
product.image.path=upload/images/Products/ProductImages/
product.default.image.path=upload/images/Products/Default/